### ISSUE TITLE
Error in node.js example

### ISSUE THREAD

**Issue by Tug** [GoogleCloudPlatform/google-cloud-datastore#51]
Running nodejs example adams.js I get the following error:
```
polo@gcloud-test:~/google-cloud-datastore-master/nodejs/demos/trivial$ node adams.js nirror-cloud

/home/polo/google-cloud-datastore-master/nodejs/demos/trivial/adams.js:56
  this.credentials.authorize((function(computeErr) {
                   ^
TypeError: Object #<Compute> has no method 'authorize'
    at Adams.authorize (/home/polo/google-cloud-datastore-master/nodejs/demos/trivial/adams.js:56:20)
    at new Adams (/home/polo/google-cloud-datastore-master/nodejs/demos/trivial/adams.js:45:8)
    at Object.<anonymous> (/home/polo/google-cloud-datastore-master/nodejs/demos/trivial/adams.js:208:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Is this related to issue #43 ?

**Comment by eddavisson** [comment]
Closing since we've removed the Node.js sample from the repo.

Check out [gcloud-node](https://github.com/GoogleCloudPlatform/gcloud-node#google-cloud-datastore) as an option for accessing Google Cloud Datastore from Node.
