### ISSUE TITLE
LocalDevelopmentDatastore cannot start gcd - "Server did not start normally"

### ISSUE THREAD

**Issue by jkff** [GoogleCloudPlatform/google-cloud-datastore#53]
I'm trying to use LocalDevelopmentDatastore according to its documentation. However, it seems to be using an unsupported option --allow_remote_shutdown of gcd.sh.

How to reproduce:
* Download gcd tool from https://cloud.google.com/datastore/docs/downloads , I downloaded version 1.2.1.0.
* Create the following example:
```
import com.google.api.services.datastore.client.DatastoreOptions;
import com.google.api.services.datastore.client.LocalDevelopmentDatastore;
import com.google.api.services.datastore.client.LocalDevelopmentDatastoreFactory;
    
class Example {
  public static void main(String[] args) throws Exception {
    LocalDevelopmentDatastore datastore;
    DatastoreOptions opts = new DatastoreOptions.Builder()
        .host("http://localhost:8080")
        .dataset("myapp")
        .build();
    datastore = LocalDevelopmentDatastoreFactory.get().create(opts);
    datastore.start("......../path/to/google-cloud-datastore-sdk/gcd", "myapp");
  }
}
```
* Download dependencies
* Compile:
```
javac -cp google-api-services-datastore-protobuf-v1beta2-rev1-2.1.0.jar Example.java 
```
* Run:
```
java -cp google-api-services-datastore-protobuf-v1beta2-rev1-2.1.0.jar:google-http-client-1.19.0.jar:protobuf-java-2.5.0.jar:. Example
```

I get an exception:
```
Nov 24, 2014 10:54:58 AM com.google.api.services.datastore.client.DatastoreFactory makeClient
WARNING: Not using any credentials
Unexpected option(s): myapp --allow_remote_shutdown.
Exiting.
Exception in thread "main" com.google.api.services.datastore.client.LocalDevelopmentDatastoreException: Server did not start normally
	at com.google.api.services.datastore.client.LocalDevelopmentDatastore.startDatastoreInternal(LocalDevelopmentDatastore.java:164)
	at com.google.api.services.datastore.client.LocalDevelopmentDatastore.start(LocalDevelopmentDatastore.java:132)
	at Example.main(Example.java:13)
```

**Comment by eddavisson** [comment]
This was fixed a while back.
