### ISSUE TITLE
Datastore is throwing I/O error while interacting with cloud API

### ISSUE THREAD

**Issue by pradex** [GoogleCloudPlatform/google-cloud-datastore#86]
My code is working perfectly when i run it locally along with gcd tool, but when i am deploying my application everytime i am trying to add a row it throws an I/O error. Please help me understand what am i missing here?
Here is my code:
```
//Creating datastore instance
Datastore datastore = DatastoreHelper.getDatastoreFromEnv();

//Interacting with datastore according to Greeting example
public void addTemplate(String id, String name, String data) throws DatastoreException {
    Entity.Builder template = Entity.newBuilder();
    template.setKey(makeKey(TEMPLATE_KIND, "template",TEMPLATE_TABLE));
    template.addProperty(makeProperty(ID_PROPERTY, makeValue("temp" + id)));
    template.addProperty(makeProperty(TEMPLATE_NAME, makeValue(name)));
    template.addProperty(makeProperty(DATA, makeValue(data)));
    template.addProperty(makeProperty(DATE_PROPERTY, makeValue(new Date())));

    List<Key> templateKey = insertAutoId(template.build());
    log.info("Template key is: {}", templateKey.get(0));
  }

  List<Key> insertAutoId(Entity... entities) throws DatastoreException {
    DatastoreV1.Mutation.Builder mutation = DatastoreV1.Mutation.newBuilder();
    for (Entity entity : entities) {
      mutation.addInsertAutoId(entity);
    }
    CommitRequest req = CommitRequest.newBuilder()
        .setMutation(mutation)
        .setMode(CommitRequest.Mode.NON_TRANSACTIONAL)
        .build();
    log.info("Datastore Req is {}", req);
    return datastore.commit(req).getMutationResult().getInsertAutoIdKeyList();
  } 
```
This is the error i am getting when i make a Rest call to above code.

```
com.google.api.services.datastore.client.DatastoreException: I/O error
	at com.google.api.services.datastore.client.RemoteRpc.makeException(RemoteRpc.java:115) ~[communication-svc.jar:0.0.1]
	at com.google.api.services.datastore.client.RemoteRpc.call(RemoteRpc.java:83) ~[communication-svc.jar:0.0.1]
	at com.google.api.services.datastore.client.BaseDatastoreFactory$RemoteRpc.call(BaseDatastoreFactory.java:41) ~[communication-svc.jar:0.0.1]
	at com.google.api.services.datastore.client.Datastore.commit(Datastore.java:85) ~[communication-svc.jar:0.0.1]
	at com.plystash.communication.db.SmsDatastoreDao.insertAutoId(SmsDatastoreDao.java:66) ~[communication-svc.jar:0.0.1]
	at com.plystash.communication.db.SmsDatastoreDao.addTemplate(SmsDatastoreDao.java:52) ~[communication-svc.jar:0.0.1]
	at com.plystash.communication.resources.TemplateStoreResource.addTemplate(TemplateStoreResource.java:28) ~[communication-svc.jar:0.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
.......

```

**Comment by pradex** [comment]
This is resolved as i figured that i was passing DATASTORE_HOST value as system env which i shouldn't pass when i'm trying to connect to Cloud API and not local datastore.
